namespace WebApplication6.Migrations
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;
    using WebApplication6.Models;

    internal sealed class Configuration : DbMigrationsConfiguration<WebApplication6.DAL.VoyageContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = true;
        }

        protected override void Seed(WebApplication6.DAL.VoyageContext context)
        {

            context.Cities.AddOrUpdate(
                c => c.CityId,
                new City { CityId=10001, CityName="Paris" },
                new City { CityId=10002, CityName="Marseille" },
                new City { CityId=10003, CityName="Lyon" },
                new City { CityId=10004, CityName="Toulouse" },
                new City { CityId=10005, CityName="Nantes" }
            );
            
            context.ScenicSpots.AddOrUpdate(
                s => s.ScenicSpotId,
                new ScenicSpot { ScenicSpotId = 10011, ScenicSpotName = "Notre-Dame de Paris", ScenicSpotDetails = "This Gothic marvel5 of architecture is more than a building; it is an symbolic element of the city, listed by UNESCO as a world heritage site. Notre Dame Cathedral was built between the 12th and 14th centuries. In Notre Dame Cathedral, there are three rose windows (large, round, stained glass windows) that have original glass. These were saved during the war by being removed and hidden in the countryside. They were later fully reinstalled.", TicketPrice = 120, OpeningHour = DateTime.Parse("8:00"), ClosingHour = DateTime.Parse("18:00"), CityId = 10001 },
                new ScenicSpot { ScenicSpotId = 10012, ScenicSpotName = "Musee du Louvre", ScenicSpotDetails = "The Musee Du Louvre (French pronunciation: [myze dy luvʁ]) – in English, the Louvre Museum or simply the Louvre – is one of the world's largest museums, the most visited art museum in the world and a historic monument. A central landmark of Paris, it is located on the Right Bank of the Seine in the 1st arrondissement (district). Nearly 35,000 objects from prehistory to the 19th century are exhibited over an area of 60,600 square metres (652,300 square feet). The museum is housed in the Louvre Palace (Palais du Louvre) which began as a fortress built in the late 12th century under Philip II. Remnants of the fortress are visible in the basement of the museum. The building was extended many times to form the present Louvre Palace. In 1682, Louis XIV chose the Palace of Versailles for his household, leaving the Louvre primarily as a place to display the royal collection, including, from 1692, a collection of antique sculpture.[4] In 1692, the building was occupied by the Académie des Inscriptions et Belles Lettres and the Académie Royale de Peinture et de Sculpture, which in 1699 held the first of a series of salons. The Académie remained at the Louvre for 100 years.[5] During the French Revolution, the National Assembly decreed that the Louvre should be used as a museum, to display the nation's masterpieces. The museum opened on 10 August 1793 with an exhibition of 537 paintings, the majority of the works being royal and confiscated church property. Because of structural problems with the building, the museum was closed in 1796 until 1801. The size of the collection increased under Napoleon and the museum was renamed the Musée Napoléon. After the defeat of Napoleon at Waterloo, many works seized by his armies were returned to their original owners. The collection was further increased during the reigns of Louis XVIII and Charles X, and during the Second French Empire the museum gained 20,000 pieces. Holdings have grown steadily through donations and gifts since the Third Republic. As of 2008, the collection is divided among eight curatorial departments: Egyptian Antiquities; Near Eastern Antiquities; Greek, Etruscan, and Roman Antiquities; Islamic Art; Sculpture; Decorative Arts; Paintings; Prints and Drawings.", TicketPrice = 320, OpeningHour = DateTime.Parse("7:50"), ClosingHour = DateTime.Parse("18:50"), CityId = 10001 },
                new ScenicSpot { ScenicSpotId = 10013, ScenicSpotName = "La Tour Eiffel", ScenicSpotDetails = "The Eiffel Tower is an iron tower built on the Champ de Mars beside the Seine River in Paris. The tower has become a global icon of France and is one of the most recognizable structures in the world. Since the beginning of the 20th century, the tower has been used for radio transmission. Until the 1950s, an occasionally modified set of antenna wires ran from the summit to anchors on the Avenue de Suffren and Champ de Mars. They were connected to long-wave transmitters in small bunkers; in 1909, a permanent underground radio centre was built near the south pillar and still exists today.[citation needed] On 20 November 1913, the Paris Observatory, using the Eiffel Tower as an antenna, exchanged sustained wireless signals with the United States Naval Observatory which used an antenna in Arlington, Virginia. The object of the transmissions was to measure the difference in longitude between Paris and Washington, D.C.", TicketPrice = 180, OpeningHour = DateTime.Parse("8:00"), ClosingHour = DateTime.Parse("16:00"), CityId = 10001 },
                new ScenicSpot { ScenicSpotId=10014, ScenicSpotName="Les Champs Elysees", ScenicSpotDetails="The Champs Elysees is one of the most famous streets in the world； line with its cinemas, cafe and luxuryspecialty shops. The sidewalks are incredibly wide and lavish， leaving plenty room for a wide array of sidewalk cafes, beverage and dining options running the full range from McDonald's to posh and pricey Frenchrestaurants. Except to pay at least ＄4 for a beer or ＄9 for a mixed drink in even the modest sidewalk cafes —— wellworth the price for a table with a view of the activity on the Champs. At the very heart of Paris it is one of the most symbolic palaces in the city， representative of its spirit and its glory.", TicketPrice=200, OpeningHour=DateTime.Parse("8:00"), ClosingHour=DateTime.Parse("16:00"), CityId=10001 },
                new ScenicSpot { ScenicSpotId = 10021, ScenicSpotName = "Basilique Notre", ScenicSpotDetails = "Take a left turn from the quai DE Rive Neuve in the old port, and then walk up the ramp for about 20 minutes to get to the jaird Notre Dame. In Notre Dame there are many model ships that pray for peace. At the same time, there is still a remnant of world war ii, the German army against the British and American forces and left the scars of the wall. Looking down at marseille, and looking at the Mediterranean view. Facing the sunset, it is easy to think of north Africa.", TicketPrice = 250, OpeningHour = DateTime.Parse("8:30"), ClosingHour = DateTime.Parse("16:30"), CityId = 10002 },
                new ScenicSpot { ScenicSpotId=10022, ScenicSpotName="Marseille Old Port", ScenicSpotDetails="The old port of Marseilles is the true center of Marseilles. Early in the morning, you can hear people talking about the harvest of fishing in the first night. The two sides of the harbor are st. John's castle and st. Nicholas castle, which were built in the time of Louis XIV. The old port was not really old, he was rebuilt after world war ii, but locals still call it 'old port', except for the habit of having a historical feeling in it. Every morning the fish market is lively and the docks are full of small fishing boats and small boats. Sitting on the ferry, you can hear the sea and feel the ocean atmosphere that dominates it. The atmosphere is stronger in the maasai commercial port, the largest port on France's Mediterranean coast. There used to be a single-deck galleon that was used to sell slaves in the old harbor. The prosperity of the commercial port led to the appearance of the slave town, and today, the italian-style square is busy for dinner.", TicketPrice=130, OpeningHour=DateTime.Parse("9:00"), ClosingHour=DateTime.Parse("16:30"), CityId=10002 },
                new ScenicSpot { ScenicSpotId = 10023, ScenicSpotName = "Mediterranean", ScenicSpotDetails = "The entrance of the port city of Marseille in France, back against the blue of the Mediterranean, sits a dark net decoration by giant concrete cube construction, it is a new completion of Europe and the Mediterranean civilization museum. As the European capital of culture an important part of urban planning, Marseille hope to Europe and the Mediterranean civilization as the theme of the museum can help its torsional rearms, gang fights, drug trafficking, political corruption and other negative image of the city.", TicketPrice = 300, OpeningHour = DateTime.Parse("9:00"), ClosingHour = DateTime.Parse("17:00"), CityId = 10002 },
                new ScenicSpot { ScenicSpotId = 10024, ScenicSpotName = "Iff Island", ScenicSpotDetails = "Iff island is the smallest island in Marseilles. The island is 300 meters long and 180 meters wide. At first, the island was uninhabited, and king Francis I, in 1516, was fully aware of its defensive value, and ordered the building of a fortress, the chateau d 'if. It was an indestructible work, and later became a state prison, where he had imprisoned many princes, the descendants of princes and nobles (such as mirabbo), as well as protestants, political prisoners and revolutionaries.", TicketPrice = 270, OpeningHour = DateTime.Parse("8:10"), ClosingHour = DateTime.Parse("17:30"), CityId = 10002 },
                new ScenicSpot { ScenicSpotId = 10031, ScenicSpotName = "Place de Fourviere", ScenicSpotDetails = "Mount Fu is a major symbol of Lyon, the cradle of Lyon and the birthplace of Lyon's Christianity. Tourists can walk up or take the cable car up the mountain. The peak is the commanding height of Lyon, which overlooks the scenery of Lyon and is also a good place to enjoy the night view. There is a Catholic Frauenkirche in the mountains, built in nineteenth Century as a baroque style. On the south side are the ancient Rome arena and the Rome Gaul Museum.", TicketPrice = 400, OpeningHour = DateTime.Parse("8:00"), ClosingHour = DateTime.Parse("17:30"), CityId = 10003 },
                new ScenicSpot { ScenicSpotId = 10032, ScenicSpotName = "Place des Terreaux", ScenicSpotDetails = "Place des Terreaux is a square in the center of Lyon, France, on the peninsula between the Rona and the Thorne River, the first section of the foothills of the crerus. The whole area of the square is listed as the world heritage site by UNESCO. The famous Butler fountain (La Fontaine Bartholdi) on the square is named by its designer, the French sculptor Federick Augustus Battledi (Frederic Auguste Bartholdi), and his most famous work is Statue of Liberty. The fountain portrays the return of four black horse traced chariots from hell, and four black horses symbolizing the four rivers of France: Seine River, the Royall River, the Rona River and the galon river. She was the goddess of abundance, and when she returned to the world, it also heralded the arrival of spring.", TicketPrice = 100, OpeningHour = DateTime.Parse("9:30"), ClosingHour = DateTime.Parse("17:00"), CityId = 10003 },
                new ScenicSpot { ScenicSpotId = 10033, ScenicSpotName = "Rue du Premier Film", ScenicSpotDetails = "yon was the birthplace of the film. In March 19, 1895, Lumiere brothers used the La sortie des Ouvriers (the gate of the factory) to mark the formal birth of the film with his invention and photography concurrently. In memory of the two great figures, their former residence was changed to Institut Lumi re, which is now available. Here is the gathering place of filmmakers, a collection of old film films and preservation of the classic technology of the original films. If you have time, you can go to a movie theater in the college to see a movie.", TicketPrice = 230, OpeningHour = DateTime.Parse("10:00"), ClosingHour = DateTime.Parse("18:00"), CityId = 10003 },
                new ScenicSpot { ScenicSpotId = 10034, ScenicSpotName = "Vieux Lyon", ScenicSpotDetails = "The old city area of Lyon is located on the right bank of the Sahn river. At the foot of Mount Fu Wei, it is a fishing village in ancient times. In fifteenth Century, it became one of the largest silk goods in the world. In seventeenth Century, it was the political, economic and cultural center of France. Today, there are still many ancient buildings in the 15-17 century. Many medieval, Renaissance and classical houses were connected to each other. The streets were paved with pebbles and walked back to the middle ages. Boutique, handcraftsmen, restaurants, and cafes stand up in the street. At the same time, don't forget to look up at the street building. The colorful small house is very bright, the monster shaped drain, and the strange stone carving on the window lattice all endow the old city with the charm.", TicketPrice = 200, OpeningHour = DateTime.Parse("10:00"), ClosingHour = DateTime.Parse("16:00"), CityId = 10003 },
                new ScenicSpot { ScenicSpotId = 10041, ScenicSpotName = "Cathedrale St-Etienne", ScenicSpotDetails = "France is the most visited country in the world. It has everything that you could ever want to see on your holidays: a great city like Paris, good beaches, more monuments than any other country, lovely nature, incredible mountain scenery; need I go on? France is also a very pleasant place to stay. It has good food, great wines and people enjoy their lives. And the best thing is, maybe apart from Paris, living in France does not have to be expensive. The North of France consists of the flatlands around the town of Lille and the Channel. The area will remind visitors in many ways of Belgium and the Netherlands. The Grand' Place in Lille for example is a lot like that of Brussels.", TicketPrice = 300, OpeningHour = DateTime.Parse("9:30"), ClosingHour = DateTime.Parse("17:40"), CityId = 10004 },
                new ScenicSpot { ScenicSpotId = 10042, ScenicSpotName = "Place du Capitole", ScenicSpotDetails = "In twentieth Century, the Toulouse city hall area, 2 hectares, was redesigned. Some of the interior of the city hall can be traced back to sixteenth Century. The current side is 135 meters long and is built with pink tiles. The neoclassical architectural style, built in 1750, was designed by Gourome Cammas (Guillaume Cammas). The old town government's working place was very impressive, especially the white marble column in front of it. In 1873, Viole Le Duke built a typical bell tower in the north of France on the top of the watchtower. It was in this watchtower that Jean Calas was questioned for religious bias. In the original medieval architecture, only Henry IV's courtyards and doors survived. It was in this courtyard that Prince Duke of Monte Carlo went out of his way to oppose cardinal Richelieu. In 1995, the plaza was completely redesigned, retaining the pedestrian's space. Today, there are also Opera Company and Symphony Orchestra in the city hall.", TicketPrice = 350, OpeningHour = DateTime.Parse("9:40"), ClosingHour = DateTime.Parse("17:00"), CityId = 10004 },
                new ScenicSpot { ScenicSpotId = 10043, ScenicSpotName = "Cite de l'Espace", ScenicSpotDetails = "The space city is located in the plain Park in eastern Toulouse. It is a famous aviation museum and astronomical theme park in France. The space city is a good place for exploring, experimentation, and understanding of the universe. There are seven exhibitions of different themes. Visitors can have a broader understanding of the universe in many ways. The famous milkspace station shows some space stations to learn about the lives and work of the astronauts living here, and the 53 - meter - high Ariana five full size rocket model stands high and is a big sign of the space city.", TicketPrice = 330, OpeningHour = DateTime.Parse("8:30"), ClosingHour = DateTime.Parse("16:50"), CityId = 10004 },
                new ScenicSpot { ScenicSpotId = 10051, ScenicSpotName = "Parc des Chantiers", ScenicSpotDetails = "With the amusement park created by the science fiction world view of the author of twenty thousand li, the amusement facilities are common, but the mechanical animals are worth seeing, and it is probably better to see it as an amusement park than a small museum. In particular the most symbolic giant elephant, 12 meters tall and 21 meters in length, the whole structure is made up of nearly 50 tonnes of steel. It is 2000 liters of lubricating oil used to maintain mechanical operation, and the thick skin of the shell uses American tulip wood. Usually it lives in a steel building on a ship's central street. In building, when it stepped out, the tremendous pressure and shock brought by this huge monster was unrivaled.", TicketPrice = 450, OpeningHour = DateTime.Parse("8:30"), ClosingHour = DateTime.Parse("16:30"), CityId = 10005 },
                new ScenicSpot { ScenicSpotId = 10052, ScenicSpotName = "Rue Georges Clemenceau", ScenicSpotDetails = "The art exhibits in Nantes art museum are very rich. There are many paintings from the thirteenth Century to the present. There is also a exhibition hall to show the works of Kandinsky. The parts of the ancient works and the Impressionists and the wild animals of the modern art are not always worth seeing.", TicketPrice = 160, OpeningHour = DateTime.Parse("8:00"), ClosingHour = DateTime.Parse("16:00"), CityId = 10005 }
            );
            
            context.Images.AddOrUpdate(
                i => i.ImageFilename,
                new Image { ImageFilename = "../../Images/Paris/Notre-Dame de Paris1.jpeg", ScenicSpotId = 10011 },
                new Image { ImageFilename = "../../Images/Paris/Notre-Dame de Paris2.jpeg", ScenicSpotId = 10011 },
                new Image { ImageFilename = "../../Images/Paris/Musee du Louvre1.jpeg", ScenicSpotId = 10012 },
                new Image { ImageFilename = "../../Images/Paris/Musee du Louvre2.jpeg", ScenicSpotId = 10012 },
                new Image { ImageFilename = "../../Images/Paris/La Tour Eiffel1.jpeg", ScenicSpotId = 10013 },
                new Image { ImageFilename = "../../Images/Paris/La Tour Eiffel2.jpeg", ScenicSpotId = 10013 },
                new Image { ImageFilename = "../../Images/Paris/Les Champs Elysees1.jpeg", ScenicSpotId = 10014 },
                new Image { ImageFilename = "../../Images/Paris/Les Champs Elysees2.jpeg", ScenicSpotId = 10014 },
                new Image { ImageFilename = "../../Images/Marseille/Basilique Notre1.jpg", ScenicSpotId = 10021 },
                new Image { ImageFilename = "../../Images/Marseille/Basilique Notre2.jpg", ScenicSpotId = 10021 },
                new Image { ImageFilename = "../../Images/Marseille/Marseille Old Port1.jpg", ScenicSpotId = 10022 },
                new Image { ImageFilename = "../../Images/Marseille/Marseille Old Port2.jpg", ScenicSpotId = 10022 },
                new Image { ImageFilename = "../../Images/Marseille/Mediterranean1.jpg", ScenicSpotId = 10023 },
                new Image { ImageFilename = "../../Images/Marseille/Mediterranean2.jpg", ScenicSpotId = 10023 },
                new Image { ImageFilename = "../../Images/Marseille/Iff Island1.jpg", ScenicSpotId = 10024 },
                new Image { ImageFilename = "../../Images/Marseille/Iff Island2.jpg", ScenicSpotId = 10024 },
                new Image { ImageFilename = "../../Images/Lyon/Place de Fourviere1.jpg", ScenicSpotId = 10031 },
                new Image { ImageFilename = "../../Images/Lyon/Place de Fourviere2.jpg", ScenicSpotId = 10031 },
                new Image { ImageFilename = "../../Images/Lyon/Place des Terreaux1.jpg", ScenicSpotId = 10032 },
                new Image { ImageFilename = "../../Images/Lyon/Place des Terreaux2.jpg", ScenicSpotId = 10032 },
                new Image { ImageFilename = "../../Images/Lyon/Rue du Premier Film1.jpg", ScenicSpotId = 10033 },
                new Image { ImageFilename = "../../Images/Lyon/Rue du Premier Film2.jpg", ScenicSpotId = 10033 },
                new Image { ImageFilename = "../../Images/Lyon/Vieux Lyon1.jpg", ScenicSpotId = 10034 },
                new Image { ImageFilename = "../../Images/Lyon/Vieux Lyon2.jpg", ScenicSpotId = 10034 },
                new Image { ImageFilename = "../../Images/Toulouse/Cathedrale St-Etienne1.jpeg", ScenicSpotId = 10041 },
                new Image { ImageFilename = "../../Images/Toulouse/Cathedrale St-Etienne2.jpeg", ScenicSpotId = 10041 },
                new Image { ImageFilename = "../../Images/Toulouse/Place du Capitole1.jpeg", ScenicSpotId = 10042 },
                new Image { ImageFilename = "../../Images/Toulouse/Place du Capitole2.jpeg", ScenicSpotId = 10042 },
                new Image { ImageFilename = "../../Images/Toulouse/Cite de l'Espace1.jpeg", ScenicSpotId = 10043 },
                new Image { ImageFilename = "../../Images/Toulouse/Cite de l'Espace2.jpeg", ScenicSpotId = 10043 },
                new Image { ImageFilename = "../../Images/Nantes/Parc des Chantiers1.jpg", ScenicSpotId = 10051 },
                new Image { ImageFilename = "../../Images/Nantes/Parc des Chantiers2.jpg", ScenicSpotId = 10051 },
                new Image { ImageFilename = "../../Images/Nantes/Rue Georges Clemenceau1.jpg", ScenicSpotId = 10052 },
                new Image { ImageFilename = "../../Images/Nantes/Rue Georges Clemenceau2.jpg", ScenicSpotId = 10052 }
            );
            /*
            context.ReviewTexts.AddOrUpdate(
                r => r.ReviewId,
                new ReviewText { ReviewId=, ReviewTextDetails= },
                new ReviewText { ReviewId=, ReviewTextDetails= },
                new ReviewText { ReviewId=, ReviewTextDetails= },
                new ReviewText { ReviewId=, ReviewTextDetails= },
                new ReviewText { ReviewId=, ReviewTextDetails= },
                new ReviewText { ReviewId=, ReviewTextDetails= },
                new ReviewText { ReviewId=, ReviewTextDetails= },
                new ReviewText { ReviewId=, ReviewTextDetails= },
                new ReviewText { ReviewId=, ReviewTextDetails= },
                new ReviewText { ReviewId=, ReviewTextDetails= },
                new ReviewText { ReviewId=, ReviewTextDetails= },
                new ReviewText { ReviewId=, ReviewTextDetails= },
                new ReviewText { ReviewId=, ReviewTextDetails= },
                new ReviewText { ReviewId=, ReviewTextDetails= },
                new ReviewText { ReviewId=, ReviewTextDetails= },
                new ReviewText { ReviewId=, ReviewTextDetails= },
                new ReviewText { ReviewId=, ReviewTextDetails= }
            );*/
        }
    }
}
